# CRE Project Settings for Aletheia Prediction Market Oracle

local-simulation:
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://virtual.mainnet.eu.rpc.tenderly.co/7ab2ac7f-6262-4a2d-9271-11cb2f95b651

staging:
  cre-cli:
    don-family: "zone-a"
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://virtual.mainnet.eu.rpc.tenderly.co/7ab2ac7f-6262-4a2d-9271-11cb2f95b651
